payton : add more files based on logcat
needed for camera.

05-23 11:38:06.662  1558  1558 I android.hardware.camera.provider@2.4-service: Camera provider Service is starting.
05-23 11:38:06.665  1558  1558 D vndksupport: Loading /vendor/lib/hw/android.hardware.camera.provider@2.4-impl.so from current namespace instead of sphal namespace.
05-23 11:38:06.678  1558  1558 D vndksupport: Loading /vendor/lib/hw/camera.sdm660.so from current namespace instead of sphal namespace.
05-23 11:38:06.680  1558  1558 E HAL     : load: module=/vendor/lib/hw/camera.sdm660.so
05-23 11:38:06.680  1558  1558 E HAL     : dlopen failed: library "libhal_dbg.so" not found
05-23 11:38:06.680  1558  1558 E CamProvider@2.4-impl: Could not load camera HAL module: -22 (Invalid argument)
05-23 11:38:06.680  1558  1558 E CamProvider@2.4-impl: HIDL_FETCH_ICameraProvider: camera provider init failed!
05-23 11:38:06.681  1558  1558 E android.hardware.camera.provider@2.4-service: Could not get passthrough implementation for android.hardware.camera.provider@2.4::ICameraProvider/legacy/0.

and a sensor

05-23 11:38:03.752   734   734 W qti_sensors_hal: addSensor : Not supported sensor with handle 49!
05-23 11:38:03.752   734   734 W qti_sensors_hal: addSensor : Not supported sensor with handle 50!
05-23 11:38:03.752   734   734 W qti_sensors_hal: addSensor : Not supported sensor with handle 54!
05-23 11:38:03.754   734   734 W qti_sensors_hal: addSensor : Not supported sensor with handle 69!
05-23 11:38:03.767   734   734 E libsensor1: client_get_conn: qmi_client_get_service_list error -2
05-23 11:38:03.767   734   734 E libsensor1: sensor1_write: Unable to create client connection
05-23 11:38:03.768   734   734 E qti_sensors_hal: sendAlgoAttribReq: sensor1_write() error: 12
05-23 11:38:03.776   734   734 I         : Loaded library from sensors.ssc.so
05-23 11:38:03.777   734   734 W         : dlerror(): dlopen failed: library "sensors.rp.so" not found
05-23 11:38:03.777   734   734 E /vendor/bin/hw/android.hardware.sensors@1.0-service: HAL specifies version 1.4, but does not implement set_operation_mode()
05-23 11:38:03.778   769   939 D vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.